version: '3.8'

services:
  # Backend API servisi
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: saticiyz-backend
    environment:
      - NODE_ENV=development
      - PORT=5000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - saticiyz-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Frontend servisi
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: saticiyz-frontend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_SUPABASE_URL=${SUPABASE_URL}
      - REACT_APP_SUPABASE_KEY=${SUPABASE_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - saticiyz-network

networks:
  saticiyz-network:
    driver: bridge 